on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: sync to S3
        run: aws s3 sync . s3://ajwpak-cloudresumechallenge --exclude ".git/*" --delete
      - name: CloudFront invalidation
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: >
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION"
          --paths "/count.js" "/index.html" "/style.css"
